---
- name: Installing Required packages
  ansible.builtin.package:
    name:
      - httpd
    state: present

- name: Copying server files
  ansible.builtin.copy:
    src: www
    dest: /var
    owner: root
    group: root
    mode: '0755'

- name: Copying main.js template
  ansible.builtin.template:
    src: www/html/js/main.js.j2
    dest: /var/www/html/js/main.js
    owner: root
    group: root
    mode: '0755'

- name: Adding http service to firewalld
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Starting web service
  ansible.builtin.service:
    name: httpd
    state: restarted
